feat(SI-11733)-detail-page-layout
ProfessionalHeadbanger/test_app pull request #5
Opened 2024-12-17 10:38 UTC by ProfessionalHeadbanger

- created detail page layout
- set up navigation to move from first screen to the page

2024-12-17 10:41 UTC, ProfessionalHeadbanger commented
https://github.com/user-attachments/assets/bec6c87e-af05-4a3b-8a8f-51da9e696cac

2024-12-18 09:26 UTC, danyaao requested changes

2024-12-18 09:26 UTC, danyaao commented on lib/core/themes/colors.dart
>    static const primaryText = Color(0xff000000);
Жду ThemeExtension

2024-12-18 09:26 UTC, danyaao commented on lib/core/themes/theme.dart
> +      navLargeTitleTextStyle: TextStyle(
Для текстовых стилей тоже лучше будет реализовать ThemeExtension

2024-12-18 09:26 UTC, danyaao commented on lib/features/navigation/app_routes.dart
> +class AppRoutes {
Не очень подходящее название

2024-12-18 09:26 UTC, danyaao commented on lib/features/navigation/app_routing.dart
> +        final photo = state.extra! as Photo;
Я бы добавил проверки на тип и на null, выглядит не очень безопасно

2024-12-18 09:26 UTC, danyaao commented on lib/features/photolist/presentation/pages/detail_page.dart
> +              '< ${context.l10n.back}',
Там не совсем стрелочка, там иконка. Лучше использовать что-то другое, можно GestureDetector

2024-12-18 09:26 UTC, danyaao commented on lib/features/photolist/presentation/pages/detail_page.dart
> +                  fontWeight: FontWeight.w400),
Я заметил, что ты почти не используешь trailing comma. Надо использовать, сильно улучшает читаемость кода

2024-12-18 09:26 UTC, danyaao commented on lib/features/photolist/presentation/pages/list_page.dart
> +                        );
В верстке не должно быть никакой логики

2024-12-18 09:26 UTC, danyaao commented on lib/main.dart
>    final dio = Dio();
Выглядит не очень, нужно будет сделать полноценный DI, можно подсмотреть в нашем шаблоне

2024-12-18 09:26 UTC, danyaao commented on pubspec.yaml
>    string_to_color: ^2.0.0
А что это? Оно нам нужно?

2024-12-20 10:27 UTC, ProfessionalHeadbanger commented
- unnecessary string_to_color package removed , methods from this package realized in Utils class
- routing logic relocated from layout to bloc
- theme extensions for text styles and colors realized
- minor fixes in layout

2024-12-23 11:43 UTC, merged